name: at_wavi_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+16

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_slidable: ^0.6.0
  provider: ^6.0.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  google_fonts: ^2.1.0
  flutter_image_compress: ^1.0.0
  path_provider: ^2.0.1
  permission_handler: ^8.1.3
  at_base2e15: ^1.0.0
  youtube_player_flutter: ^8.0.0
  receive_sharing_intent: ^1.4.5
  http: ^0.13.3
  file_picker: ^4.4.0
  geocoder: ^0.2.1
  easy_debounce: ^2.0.0
  validators: ^3.0.0
  latlong2: ^0.8.0
  image_cropper: ^1.4.1
  
  html_editor_enhanced: ^2.4.0+1
  flutter_widget_from_html: ^0.8.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  at_common_flutter: ^2.0.5
  at_onboarding_flutter: ^4.0.0
  at_client_mobile: ^3.1.5
  at_client: ^3.0.9
  at_contact: ^3.0.3
  at_lookup: ^3.0.7
  at_contacts_flutter: ^4.0.0
  at_commons: ^3.0.5
  at_follows_flutter: ^3.0.5
  at_location_flutter: ^3.1.2
  uni_links: ^0.5.1
  html_character_entities: 1.0.0+1

  flutter_dotenv: ^5.0.2  

dependency_overrides:
  at_follows_flutter:
    git:
      url: git@github.com:atsign-foundation/at_widgets.git
      ref: fix/at_follows_flutter_example
      path: at_follows_flutter
  flutter_colorpicker: ^0.6.0 #because html_editor_enhanced uses 0.4.0, which gives flutter event errors
  at_sync_ui_flutter:
    git:  
      url: https://github.com/atsign-foundation/at_widgets.git
      path: at_sync_ui_flutter
      ref: feature/at-sync-ui
      
  webview_flutter: ^3.0.0
  biometric_storage: ^4.0.1

  at_contact:
    git:
      url: git@github.com:atsign-foundation/at_libraries.git
      ref: fix_create_group
      path: at_contact

  at_client:
    git:
      url: git@github.com:atsign-foundation/at_client_sdk.git
      ref: switch_atsign_bug
      path: at_client
  at_client_mobile:
    git:
        url: git@github.com:atsign-foundation/at_client_sdk.git
        ref: switch_atsign_bug
        path: at_client_mobile
  at_contacts_flutter:
    git:
      url: git@github.com:atsign-foundation/at_widgets.git
      ref: trunk
      path: at_contacts_flutter
  at_contacts_group_flutter:
    git:
      url: git@github.com:atsign-foundation/at_widgets.git
      ref: trunk
      path: at_contacts_group_flutter
  at_onboarding_flutter:
    git:
      url: git@github.com:atsign-foundation/at_widgets.git
      ref: trunk
      path: at_onboarding_flutter 
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 500
      
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
